/*
 * Netbeans 8.0 
 * JDK 1.7  
 */
package lcm.view;

import java.util.List;
import javax.swing.JLabel;
import lcm.Ishihara;
import lcm.Plate;
import lcm.component.TableCellRenderer;
import lcm.component.TableModelResult;
import swingx.component.table.renderer.TableCellAlignmentRenderer;

/**
 *
 * @author casper
 */
public class PanelTestResult extends javax.swing.JPanel {

    /**
     * Creates new form PanelTestResult
     */
    private TableModelResult tableModel;

    public PanelTestResult(FrameMain main) {
        initComponents();

        
        tableModel = new TableModelResult();
        table.setModel(tableModel);

        table.getColumnModel().getColumn(0).setCellRenderer(new TableCellAlignmentRenderer(JLabel.CENTER));
        table.getColumnModel().getColumn(1).setCellRenderer(new TableCellAlignmentRenderer(JLabel.CENTER));
        table.getColumnModel().getColumn(2).setCellRenderer(new TableCellAlignmentRenderer(JLabel.CENTER));
        table.getColumnModel().getColumn(3).setCellRenderer(new TableCellAlignmentRenderer(JLabel.CENTER));
        table.getColumnModel().getColumn(4).setCellRenderer(new TableCellRenderer());

        table.getColumnModel().getColumn(0).setPreferredWidth(10);
        table.getColumnModel().getColumn(3).setPreferredWidth(10);
        table.getColumnModel().getColumn(4).setPreferredWidth(15);
        table.setRowHeight(23);
    }

    public void set(List<Plate> list) {
        Ishihara ishihara = new Ishihara(); 
        
        Object[] answer = new Object[38];
        for (int i = 0; i < list.size(); i++) {
            Plate plate = list.get(i);
            plate.setResult(ishihara.check(plate));
            plate.setCorrect(ishihara.getCorrect(plate));
            answer[i] = plate.getAnswer();
        }
        tableModel.setList(list);
        table.setModel(tableModel);
        table.revalidate();
        
        
        ishihara.setAnswer(answer);
        
        String hasil = "";
        if (!ishihara.plate1()) {
            hasil = "TOTAL COLOR BLIND";
        } else if (ishihara.plate1() && ishihara.r2()) {
            hasil = "PARSIAL COLOR BLIND";
        } else if (ishihara.plate1() && ishihara.r3()) {
            hasil = "PARSIAL COLOR BLIND";
        } else if (ishihara.plate1() && ishihara.r4()) {
            hasil = "PARSIAL COLOR BLIND";
        } else if (ishihara.plate1() && ishihara.r5()) {
            hasil = "PARSIAL COLOR BLIND";
        } else {
            hasil = "NOT COLOR BLIND (NORMAL)";
        }
        labelResult.setText("<html>According to this test you are "+hasil+"</html>".toUpperCase());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        labelResult = new javax.swing.JLabel();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        labelResult.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addComponent(labelResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelResult;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
